"use client";
import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import { Conversation, Message } from "@/lib/types";
export default function Home() { const [convs,setConvs]=useState<Conversation[]>([]),[current,setCurrent]=useState<Conversation|null>(null),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(""),[running,setRunning]=useState(false),[error,setError]=useState(""),[modelName,setModelName]=useState("gpt-4o-mini");
  const load=async()=>{const cs=await (await fetch('/api/conversations')).json();setConvs(cs);if(!current&&cs[0]) open(cs[0]);}; const open=async(c:Conversation)=>{setCurrent(c);setMessages((await (await fetch(`/api/conversations/${c.id}`)).json()).messages)}; useEffect(()=>{load();fetch('/api/model-config').then(r=>r.json()).then(c=>setModelName(c.model||'gpt-4o-mini'))},[]);
  const newChat=async()=>{const c=await (await fetch('/api/conversations',{method:'POST'})).json();setConvs(x=>[c,...x]);open(c)}; const remove=async(id:string)=>{await fetch(`/api/conversations/${id}`,{method:'DELETE'});setConvs(x=>x.filter(c=>c.id!==id));if(current?.id===id){setCurrent(null);setMessages([])}};
  const send=async()=>{if(!current||!input.trim()||running)return;const text=input.trim();setInput('');setError('');setMessages(x=>[...x,{id:'u'+Date.now(),conversationId:current.id,role:'user',content:text,createdAt:new Date().toISOString()},{id:'a'+Date.now(),conversationId:current.id,role:'assistant',content:'',createdAt:new Date().toISOString(),status:'streaming'}]);setRunning(true);const res=await fetch(`/api/conversations/${current.id}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:text})});if(!res.body){setRunning(false);return}const reader=res.body.getReader(),dec=new TextDecoder();let buf='';while(true){const {value,done}=await reader.read();if(done)break;buf+=dec.decode(value);const chunks=buf.split('\n\n');buf=chunks.pop()||'';for(const chunk of chunks){const d=chunk.split('\ndata: ')[1];if(!d)continue;const data=JSON.parse(d);if(chunk.startsWith('event: token'))setMessages(x=>{const a=[...x];a[a.length-1]={...a[a.length-1],content:a[a.length-1].content+data.token};return a});if(chunk.startsWith('event: run_failed'))setError(data.error)}}setRunning(false);load()};
  const cancel=async()=>{if(current){await fetch(`/api/conversations/${current.id}/messages`,{method:'DELETE'});setRunning(false)}};
  return <main className="chat-shell"><aside><div className="brand">helix-mini</div><div className="nav"><a href="/">对话</a><a href="/settings">模型配置</a><a href="/docs">API 文档</a><a href="/logs">运行日志</a></div><button onClick={newChat}>＋ 新建会话</button><div className="list">{convs.map(c=><div className={`item ${current?.id===c.id?'active':''}`} key={c.id} onClick={()=>open(c)}><span>{c.title}</span><button onClick={e=>{e.stopPropagation();remove(c.id)}}>×</button></div>)}</div></aside><section className="chat-panel"><header>{current?.title||'选择一个会话'}</header><div className="messages">{messages.map(m=><div className={`message ${m.role}`} key={m.id}><div className="role">{m.role==='user'?'你':'Agent'}</div><ReactMarkdown>{m.content||'…'}</ReactMarkdown></div>)}{!messages.length&&<div className="empty">创建会话，开始你的第一个任务。</div>}</div><div className="chat-footer">{error&&<div className="error">{error}</div>}<div className="composer"><div className="composer-model">当前模型：{modelName}</div><div className="composer-row"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder={`使用 ${modelName} 输入你的任务…`}/>{running?<button onClick={cancel}>停止</button>:<button onClick={send} disabled={!current}>{'发送'}</button>}</div></div></div></section></main> }
